### ISSUE TITLE
Base visualization y-axis on max data

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#23]
Depending on the challenge, being able to specify the maximum value of y-axis for visualizations would help with seeing details of the forecasts

**Comment by cdc-mgz4** [comment]
Leaving this up to configuration is not a very good solution for long term. I solved this issue by examining a project's template for the highest possible bin. This avoids observed data not being available and past issues since there's no way in the system to have data at all, without a template in place. Updating server when #22 is closed.
